//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	http "net/http"
	unsafe "unsafe"

	autoheal "github.com/openshift/autoheal/pkg/apis/autoheal"
	extension "github.com/openshift/autoheal/pkg/apis/extension"
	v1 "k8s.io/api/batch/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AWXJobAction)(nil), (*autoheal.AWXJobAction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AWXJobAction_To_autoheal_AWXJobAction(a.(*AWXJobAction), b.(*autoheal.AWXJobAction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.AWXJobAction)(nil), (*AWXJobAction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_AWXJobAction_To_v1alpha2_AWXJobAction(a.(*autoheal.AWXJobAction), b.(*AWXJobAction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BasicAuth)(nil), (*autoheal.BasicAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BasicAuth_To_autoheal_BasicAuth(a.(*BasicAuth), b.(*autoheal.BasicAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.BasicAuth)(nil), (*BasicAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_BasicAuth_To_v1alpha2_BasicAuth(a.(*autoheal.BasicAuth), b.(*BasicAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HealingRule)(nil), (*autoheal.HealingRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HealingRule_To_autoheal_HealingRule(a.(*HealingRule), b.(*autoheal.HealingRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.HealingRule)(nil), (*HealingRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_HealingRule_To_v1alpha2_HealingRule(a.(*autoheal.HealingRule), b.(*HealingRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HealingRuleList)(nil), (*autoheal.HealingRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HealingRuleList_To_autoheal_HealingRuleList(a.(*HealingRuleList), b.(*autoheal.HealingRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.HealingRuleList)(nil), (*HealingRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_HealingRuleList_To_v1alpha2_HealingRuleList(a.(*autoheal.HealingRuleList), b.(*HealingRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SelectorRequirement)(nil), (*autoheal.SelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SelectorRequirement_To_autoheal_SelectorRequirement(a.(*SelectorRequirement), b.(*autoheal.SelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.SelectorRequirement)(nil), (*SelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_SelectorRequirement_To_v1alpha2_SelectorRequirement(a.(*autoheal.SelectorRequirement), b.(*SelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Webhook)(nil), (*autoheal.Webhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Webhook_To_autoheal_Webhook(a.(*Webhook), b.(*autoheal.Webhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*autoheal.Webhook)(nil), (*Webhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_autoheal_Webhook_To_v1alpha2_Webhook(a.(*autoheal.Webhook), b.(*Webhook), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_AWXJobAction_To_autoheal_AWXJobAction(in *AWXJobAction, out *autoheal.AWXJobAction, s conversion.Scope) error {
	out.Template = in.Template
	out.ExtraVars = (*extension.AnyConfig)(unsafe.Pointer(in.ExtraVars))
	out.Limit = in.Limit
	return nil
}

// Convert_v1alpha2_AWXJobAction_To_autoheal_AWXJobAction is an autogenerated conversion function.
func Convert_v1alpha2_AWXJobAction_To_autoheal_AWXJobAction(in *AWXJobAction, out *autoheal.AWXJobAction, s conversion.Scope) error {
	return autoConvert_v1alpha2_AWXJobAction_To_autoheal_AWXJobAction(in, out, s)
}

func autoConvert_autoheal_AWXJobAction_To_v1alpha2_AWXJobAction(in *autoheal.AWXJobAction, out *AWXJobAction, s conversion.Scope) error {
	out.Template = in.Template
	out.ExtraVars = (*extension.AnyConfig)(unsafe.Pointer(in.ExtraVars))
	out.Limit = in.Limit
	return nil
}

// Convert_autoheal_AWXJobAction_To_v1alpha2_AWXJobAction is an autogenerated conversion function.
func Convert_autoheal_AWXJobAction_To_v1alpha2_AWXJobAction(in *autoheal.AWXJobAction, out *AWXJobAction, s conversion.Scope) error {
	return autoConvert_autoheal_AWXJobAction_To_v1alpha2_AWXJobAction(in, out, s)
}

func autoConvert_v1alpha2_BasicAuth_To_autoheal_BasicAuth(in *BasicAuth, out *autoheal.BasicAuth, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.SecretName = in.SecretName
	return nil
}

// Convert_v1alpha2_BasicAuth_To_autoheal_BasicAuth is an autogenerated conversion function.
func Convert_v1alpha2_BasicAuth_To_autoheal_BasicAuth(in *BasicAuth, out *autoheal.BasicAuth, s conversion.Scope) error {
	return autoConvert_v1alpha2_BasicAuth_To_autoheal_BasicAuth(in, out, s)
}

func autoConvert_autoheal_BasicAuth_To_v1alpha2_BasicAuth(in *autoheal.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.SecretName = in.SecretName
	return nil
}

// Convert_autoheal_BasicAuth_To_v1alpha2_BasicAuth is an autogenerated conversion function.
func Convert_autoheal_BasicAuth_To_v1alpha2_BasicAuth(in *autoheal.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	return autoConvert_autoheal_BasicAuth_To_v1alpha2_BasicAuth(in, out, s)
}

func autoConvert_v1alpha2_HealingRule_To_autoheal_HealingRule(in *HealingRule, out *autoheal.HealingRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.MatchExpressions = *(*[]autoheal.SelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	out.AWXJob = (*autoheal.AWXJobAction)(unsafe.Pointer(in.AWXJob))
	out.BatchJob = (*v1.JobSpec)(unsafe.Pointer(in.BatchJob))
	out.Webhook = (*autoheal.Webhook)(unsafe.Pointer(in.Webhook))
	out.DisableForResolvedMessage = (*bool)(unsafe.Pointer(in.DisableForResolvedMessage))
	return nil
}

// Convert_v1alpha2_HealingRule_To_autoheal_HealingRule is an autogenerated conversion function.
func Convert_v1alpha2_HealingRule_To_autoheal_HealingRule(in *HealingRule, out *autoheal.HealingRule, s conversion.Scope) error {
	return autoConvert_v1alpha2_HealingRule_To_autoheal_HealingRule(in, out, s)
}

func autoConvert_autoheal_HealingRule_To_v1alpha2_HealingRule(in *autoheal.HealingRule, out *HealingRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.MatchExpressions = *(*[]SelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	out.AWXJob = (*AWXJobAction)(unsafe.Pointer(in.AWXJob))
	out.BatchJob = (*v1.JobSpec)(unsafe.Pointer(in.BatchJob))
	out.Webhook = (*Webhook)(unsafe.Pointer(in.Webhook))
	out.DisableForResolvedMessage = (*bool)(unsafe.Pointer(in.DisableForResolvedMessage))
	return nil
}

// Convert_autoheal_HealingRule_To_v1alpha2_HealingRule is an autogenerated conversion function.
func Convert_autoheal_HealingRule_To_v1alpha2_HealingRule(in *autoheal.HealingRule, out *HealingRule, s conversion.Scope) error {
	return autoConvert_autoheal_HealingRule_To_v1alpha2_HealingRule(in, out, s)
}

func autoConvert_v1alpha2_HealingRuleList_To_autoheal_HealingRuleList(in *HealingRuleList, out *autoheal.HealingRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]autoheal.HealingRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_HealingRuleList_To_autoheal_HealingRuleList is an autogenerated conversion function.
func Convert_v1alpha2_HealingRuleList_To_autoheal_HealingRuleList(in *HealingRuleList, out *autoheal.HealingRuleList, s conversion.Scope) error {
	return autoConvert_v1alpha2_HealingRuleList_To_autoheal_HealingRuleList(in, out, s)
}

func autoConvert_autoheal_HealingRuleList_To_v1alpha2_HealingRuleList(in *autoheal.HealingRuleList, out *HealingRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HealingRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_autoheal_HealingRuleList_To_v1alpha2_HealingRuleList is an autogenerated conversion function.
func Convert_autoheal_HealingRuleList_To_v1alpha2_HealingRuleList(in *autoheal.HealingRuleList, out *HealingRuleList, s conversion.Scope) error {
	return autoConvert_autoheal_HealingRuleList_To_v1alpha2_HealingRuleList(in, out, s)
}

func autoConvert_v1alpha2_SelectorRequirement_To_autoheal_SelectorRequirement(in *SelectorRequirement, out *autoheal.SelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = autoheal.SelectorOperator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha2_SelectorRequirement_To_autoheal_SelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha2_SelectorRequirement_To_autoheal_SelectorRequirement(in *SelectorRequirement, out *autoheal.SelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha2_SelectorRequirement_To_autoheal_SelectorRequirement(in, out, s)
}

func autoConvert_autoheal_SelectorRequirement_To_v1alpha2_SelectorRequirement(in *autoheal.SelectorRequirement, out *SelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = SelectorOperator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_autoheal_SelectorRequirement_To_v1alpha2_SelectorRequirement is an autogenerated conversion function.
func Convert_autoheal_SelectorRequirement_To_v1alpha2_SelectorRequirement(in *autoheal.SelectorRequirement, out *SelectorRequirement, s conversion.Scope) error {
	return autoConvert_autoheal_SelectorRequirement_To_v1alpha2_SelectorRequirement(in, out, s)
}

func autoConvert_v1alpha2_Webhook_To_autoheal_Webhook(in *Webhook, out *autoheal.Webhook, s conversion.Scope) error {
	out.URL = in.URL
	out.Method = in.Method
	out.Headers = *(*http.Header)(unsafe.Pointer(&in.Headers))
	out.BasicAuth = (*autoheal.BasicAuth)(unsafe.Pointer(in.BasicAuth))
	out.Template = in.Template
	out.Proxy = in.Proxy
	return nil
}

// Convert_v1alpha2_Webhook_To_autoheal_Webhook is an autogenerated conversion function.
func Convert_v1alpha2_Webhook_To_autoheal_Webhook(in *Webhook, out *autoheal.Webhook, s conversion.Scope) error {
	return autoConvert_v1alpha2_Webhook_To_autoheal_Webhook(in, out, s)
}

func autoConvert_autoheal_Webhook_To_v1alpha2_Webhook(in *autoheal.Webhook, out *Webhook, s conversion.Scope) error {
	out.URL = in.URL
	out.Method = in.Method
	out.Headers = *(*http.Header)(unsafe.Pointer(&in.Headers))
	out.BasicAuth = (*BasicAuth)(unsafe.Pointer(in.BasicAuth))
	out.Template = in.Template
	out.Proxy = in.Proxy
	return nil
}

// Convert_autoheal_Webhook_To_v1alpha2_Webhook is an autogenerated conversion function.
func Convert_autoheal_Webhook_To_v1alpha2_Webhook(in *autoheal.Webhook, out *Webhook, s conversion.Scope) error {
	return autoConvert_autoheal_Webhook_To_v1alpha2_Webhook(in, out, s)
}
