apiVersion: v1
data:
  autoheal.yml: |
  {{- .Values.configs | toYaml | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "autoheal.fullname" . }}
  labels: {{- include "autoheal.labels" . | nindent 4 }}
