kind: HealingRule
apiVersion: autoheal.openshift.io/v1alpha2
metadata:
  name: say-hello
labels:
  alertname: "NewFriend"
batchJob:
  template:
    spec:
      containers:
        - name: python
          image: python
          command:
            - python
            - -c
            - print("Hello {{ $labels.name }}!")
      restartPolicy: Never
