kind: HealingRule
apiVersion: autoheal.openshift.io/v1alpha2
metadata:
  name: start-node-test
labels:
  alertname: "NodeDown"
awxJob:
  template: "Start node"
  extraVars:
    node: "{{ $labels.instance }}"
  limit: "{{ $labels.instance }}"
